version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    command: ["--replSet", "rs0"]
    ports:
      - "27018:27017"   # Host:Container
    volumes:
      - ./data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=woovi-playground
    restart: always

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
