export const PUB_SUB_EVENTS = {
	MESSAGE: {
		ADDED: 'MESSAGE:ADDED',
	},
	ACCOUNT: {
		ADDED: 'ACCOUNT:ADDED',
		UPDATED: 'ACCOUNT:UPDATED',
	},
	TRANSACTION: {
		CREATED: 'TRANSACTION:CREATED',
	}
} as const;
